baseurl = "https://chrisshort.net"
DefaultContentLanguage = "en"
title = "chrisshort.net"
theme = "beautifulhugo"
metaDataFormat = "toml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
#googleAnalytics = "UA-4498776-3"
paginate = 5

[permalinks]
  post = ":title/"

[Params]
  homeTitle = "Chris Short" # Set a different text for the header on the home page
  mainSections = ["post","posts"]
  subtitle = "Kubernetes | Voice of Hybrid Cloud on openshift.tv, Red Hat | CNCF Ambassador + @KubeWeekly | devopsish.com | Disabled Veteran | He/Him/His | Views solely mine"
  logo = "img/chrisshort.net.png" # Expecting square 1:1 dimensions
  favicon = "favicons/favicon.ico"
  dateFormat = "2006-01-02"
  commit = false
  rss = true
  comments = false
  readingTime = true
  wordCount = true
  useHLJS = false
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  gcse = "partner-pub-8972983586873269:7437701092" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
  since = "2003"
  selfHosted = true

[Author]
  name = "Chris Short"
  website = "https://chrisshort.net"
  email = "chris@chrisshort.net"
#  facebook = "username"
#  googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "chris-short"
#  gitlab = "chrisshort"
  devto = "chrisshort"
  twitter = "ChrisShort"
  reddit = "oaf357"
  linkedin = "thechrisshort"
#  xing = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
#  instagram = "username"
  youtube = "channel/UC8jhUEJ-K_QfDWbmpmwi4XA" # or channel/channelname
#  soundcloud = "username"
#  spotify = "chris.short"
#  bandcamp = "username"
#  itchio = "username"
#  vk = "username"
#  paypal = "username"
  telegram = "ChrisShort"
#  keybase = "chrisshort"
  twitch = "redhatopenshift"

[[menu.main]]
    identifier = "menu"
    name = "Main Menu"
    weight = 999

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20

#[[menu.main]]
#    name = "Résumé/CV"
#    url = "/resume/"
#    weight = 25

[[menu.main]]
    name = "Sponsor"
    url = "https://github.com/sponsors/chris-short"
    weight = 29

[[menu.main]]
    identifier = "speaking"
    name = "Speaking"
    weight = 888

[[menu.main]]
    parent = "speaking"
    name = "Talks Given"
    url = "/speaking/"
    weight = 890

[[menu.main]]
    parent = "speaking"
    name = "Interviews"
    url = "/interviews/"
    weight = 891

[[menu.main]]
    parent = "speaking"
    name = "Webinars"
    url = "/webinars/"
    weight = 897

[[menu.main]]
    parent = "speaking"
    name = "Abstracts"
    url = "/abstracts/"
    weight = 898

[[menu.main]]
    parent = "speaking"
    name = "NC Veterans Oral History Interview"
    url = "/nc-veterans-oral-history-program/"
    weight = 899

[[menu.main]]
    parent = "menu"
    name = "Advised by Short"
    url = "https://advisedbyshort.com/"
    weight = 5

[[menu.main]]
    parent = "menu"
    name = "DevOps News"
    url = "https://devopsish.com/"
    weight = 11

[[menu.main]]
    parent = "menu"
    name = "Kubernetes News"
    url = "https://kubeweekly.io/"
    weight = 12

[[menu.main]]
    parent = "menu"
    name = "DevOps README"
    url = "https://devopsreadme.xyz/"
    weight = 13

[[menu.main]]
    parent = "menu"
    name = "What is DevOps"
    url = "https://devopsish.com/what-is-devops/"
    weight = 19

[[menu.main]]
    parent = "menu"
    name = "Books"
    url = "/books/"
    weight = 60

[[menu.main]]
    parent = "menu"
    name = "Publications"
    url = "/publications/"
    weight = 70

[[menu.main]]
    parent = "menu"
    name = "Drawings"
    url = "/drawings/"
    weight = 80

[[menu.main]]
    parent = "menu"
    name = "Causes"
    url = "/causes/"
    weight = 90

[[menu.main]]
    parent = "menu"
    name = "Projects"
    url = "/projects/"
    weight = 99

[[menu.main]]
    parent = "menu"
    name = "Long Thoracic Nerve Palsy"
    url = "/long-thoracic-nerve-palsy/"
    weight = 100

[[menu.main]]
    parent = "menu"
    name = "Foundation for Purposeful Living"
    url = "/foundation-for-purposeful-living/"
    weight = 110

[[menu.main]]
    parent = "menu"
    name = "Amazon Wishlist"
    url = "https://cshort.co/amzn"
    weight = 119

[[menu.main]]
    parent = "menu"
    name = "Categories"
    url = "/categories/"
    weight = 120

[[menu.main]]
    parent = "menu"
    name = "Tags"
    url = "/tags/"
    weight = 130

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true